### ISSUE TITLE
Unable to resolve path to module '@hookform/error-message' 

### ISSUE THREAD

**Issue by ahmadkam2** [react-hook-form/error-message#11]
When I update react hook form version from `5.0.3` to `6.0.4`, I faced this error
` ErrorMessage component not exported from 'react-hook-form'`
after installing `npm install @hookform/error-message`

and edit the imports to 
`import { ErrorMessage } from '@hookform/error-message';`
I faced this error 
`Unable to resolve path to module '@hookform/error-message' `

**Comment by bluebill1049** [comment]
that shouldn't be the case, can you reproduce this in codesandbox?

**Comment by alexypdu** [comment]
Facing the same issue here. Also spot that `import { ErrorMessage } from '@hookform/error-message/dist';` do suppress the error.

**Comment by alexypdu** [comment]
While `import { ErrorMessage } from '@hookform/error-message';` function normally in my case, however, the ESLint error `import/no-unresolved: Unable to resolve path to module '@hookform/error-message'` arises unexpectedly, and changing the statement into `import { ErrorMessage } from '@hookform/error-message/dist';` just suppress the error unintentionally.

**Comment by phil-scott-78** [comment]
I ran into this myself. I don't have a codesandbox but I did create a barebones CRA reproduction this morning. https://github.com/phil-scott-78/error-message-repo. 

I've only done some brief troubleshooting, but looking at the files eslint is trying to resolve it looks like it isn't looking in the `dist` folder for `index.js` and is failing trying to resolve. This is on Windows fwiw

**Comment by phil-scott-78** [comment]
Well that was easy enough once I had a reproduction. Looks like a dist was missing in `package.json`. Create a PR (#12)

**Comment by bluebill1049** [comment]
patched thanks @phil-scott-78 very much.
