### ISSUE TITLE
Props as and render are not compatible

### ISSUE THREAD

**Issue by sergiohgz** [react-hook-form/error-message#14]
Hi there :wave:

I'm upgrading from react-hook-form v5 to v6 following migration guide, and I think that I have found a possible issue with `as` and `render` props.

In **v5**, when `render` prop was `children`, if both are present, both was applied (`as` as wrapper component and `children` for rendering message. Here is a CodeSandbox (forked from v5 docs) that demostrates that it works like a charm:
[![Edit react-hook-form-v5-ts-errorMessage](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-v5-ts-errormessage-tkxow?fontsize=14&hidenavigation=1&theme=dark)

But now, in **v6**, after moving `children` to `render`, it seems that `render` and `as` are mutually exclusive. If `as` prop is present, `render` prop won't be applied. Here is another CodeSandbox (forked from v6 docs) that should work like in the other but sadly not:
[![Edit react-hook-form-v6-ts-errorMessage](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-v6-ts-errormessage-ui9ik?fontsize=14&hidenavigation=1&theme=dark)

Is this an expected behaviour or an issue?

Thanks a lot, you are really awesome 🎉

**Comment by bluebill1049** [comment]
yes, you are right @sergiohgz we are trying to align with `Controller`, so it's either now, you can't use them together.

**Comment by sergiohgz** [comment]
Thanks for the fast response, awesome. 

I'm really new with this library, I'm learning by upgrading 😅.  I have found that I could bypass it by wrapping component in `render` prop with the one defined in `as` prop, like in this CodeSandbox:
[![Edit react-hook-form-v6-ts-errorMessage-bypass](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-v6-ts-errormessage-bypass-45squ?fontsize=14&hidenavigation=1&theme=dark)

Is this approach what we would see in the near future?

Thanks again 😄

**Comment by bluebill1049** [comment]
Yes correct :) it's either as or render. as is the lazy one, render give you the full props to assign.

**Comment by sergiohgz** [comment]
Perfect, this information should be in v5 to v6 migration guide. I will write it down later and make a PR.

Another time, thanks for your time @bluebill1049

**Comment by bluebill1049** [comment]
Thanks mate, PR welcome.
