### ISSUE TITLE
Add className to directly render a div

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [react-hook-form/error-message#18]
Would be cool if you could add a className parameter, which automatically generates a div with the desired classname...!

**Comment by bluebill1049** [comment]
use `render`

**Comment by h0jeZvgoxFepBQ2C** [comment]
Sure, but it would be really handy to just add className :)

**Comment by bluebill1049** [comment]
we do spread the rest props as well with `as`: https://github.com/react-hook-form/error-message/blob/master/src/ErrorMessage.tsx#L29
