### ISSUE TITLE
Maybe not IE11 compatible?

### ISSUE THREAD

**Issue by Knusperchicken** [react-hook-form/error-message#19]
Hello,

I just saw that the package _react-hook-form_ is being imported [here](https://github.com/react-hook-form/error-message/blob/b271504c947960dec251e2016441571d61eef4d0/src/ErrorMessage.tsx#L2). I haven't yet tried out myself but now I'm wondering if this package (_error-message_) is **not** IE11 compatible. If so, would it be possible to make it IE11 compatible by using the IE11 version of _react-hook-form_ somehow?

Thanks in advance.

**Comment by h0jeZvgoxFepBQ2C** [comment]
If you are using webpack, you can set something like this to make it automatically IE11 conform:

```
environment.config.merge({
  resolve: {
    alias: {
      "react-hook-form": "react-hook-form/dist/index.ie11",
    }
  },
```

**Comment by Knusperchicken** [comment]
Sorry for the delay. I'll try your suggestion and then report back as soon as I get the chance 👌🏻

**Comment by Knusperchicken** [comment]
Here I am again 🙂 Your suggestion seems to work fine, thank you 🍪
