### ISSUE TITLE
Does not work with React Hook Form v7 FormProvider

### ISSUE THREAD

**Issue by manzoorwanijk** [react-hook-form/error-message#52]
`ErrorMessage` uses V6 API, so we need to pass the `errors` prop to make it work in V7
https://github.com/react-hook-form/error-message/blob/7ac249b2766a370e1765f6b6785969b255395ecb/src/ErrorMessage.tsx#L20-L25

**Comment by jorisre** [comment]
Good catch !

@bluebill1049 What do you prefer ? 
- A new V1 for React Hook Form v7 _(like resolvers)_
- Just: 
    ```ts
    const isV7 = 'errors' in methods.formState;
    const error = get(errors || isV7 ? methods.formState.errors : methods.errors, name); 
    ```

**Comment by bluebill1049** [comment]
oops~ would you like to upgrade this package @jorisre? if you are busy, i will sort it out too.

**Comment by jorisre** [comment]
I can do it this afternoon if you're busy. Which solution do you like ?

**Comment by bluebill1049** [comment]
I think the new version makes sense.

**Comment by jorisre** [comment]
@manzoorwanijk [V2](https://github.com/react-hook-form/error-message/releases/tag/v2.0.0) is released and support React Hook Form V7 🎉

**Comment by manzoorwanijk** [comment]
Thank you.

**Comment by steveoh** [comment]
Did the syntax change with v2? The readme doesn't show anything but I'm receiving 

```js
ErrorMessage.tsx:21 Uncaught (in promise) TypeError: Cannot read property 'formState' of null
    at s (ErrorMessage.tsx:21)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
```

**Comment by jorisre** [comment]
Hi @steveoh 
The syntax didn't change with v2. V2 just support React Hook Form v7, can you provide a codesandbox with your problem please ?

**Comment by steveoh** [comment]
I think the biggest issue is that in V7 it appears that `formState` isn't exported and the diff above is how you "get it back". The diff usage seems a little awkward and I wonder if it could be improved to keep the old style of usage.
