### ISSUE TITLE
Documentation - "get" method

### ISSUE THREAD

**Issue by asotog** [react-hook-form/error-message#80]
Hi,

just found in `ErrorMessage`there exists a `get` method for digging into objects especially errors and retrieve nested values, is there any plan to document this in the API docs?

```
import * as React from 'react';
import { useFormContext, get, FieldErrors } from 'react-hook-form';
import { Props } from './types';
```
can be used like 
```
 const error = get(errors || methods.formState.errors, name);
```

This is useful when handling complex nested forms, right now documentation does not expose all the power of react hooks forms utils.
My favorite forms library by far...
Thanks in advance,

**Comment by bluebill1049** [comment]
hey @asotog thanks for the kind words, please use load dash `get` instead, hook form `get` is limited to internal use only. hence we don't document it.

**Comment by asotog** [comment]
> hey @asotog thanks for the kind words, please use load dash `get` instead, hook form `get` is limited to internal use only. hence we don't document it.

that's good idea thanks

**Comment by bluebill1049** [comment]
np :)
