### ISSUE TITLE
How to get error count

### ISSUE THREAD

**Issue by getsetgopi** [react-hook-form/error-message#84]
As per accessibility requirement we need to show total number of errors in a form.
For example: 

1. A form with First name, Last name, email, age, telephone are required field. 
2. User clicks on submit without entering any value to input fields.
3. We need to show a message on top of the page as "There are 5 errors". Screen reader will announce this message (helpful for non-sighted user).

I tried error.length and did not work. Want to know how can I achieve this to full fill accessibility requirement.

**Comment by bluebill1049** [comment]
you will need to use Object.keys with .length instead.
