### ISSUE TITLE
`as` prop does not take precedence over components

### ISSUE THREAD

**Issue by IanVS** [react-hook-form/error-message#88]
As seen in https://github.com/react-hook-form/error-message/pull/87#discussion_r714144172, `as` does not take precedence over `render` if the value provided to it is a component rather than an element.

The snapshot generated in https://github.com/react-hook-form/error-message/pull/87 is not correct, and should be fixed.

**Comment by bluebill1049** [comment]
Thank you very much @IanVS sorry for the delay response. Merged and released.

**Comment by IanVS** [comment]
The PR mentioned above #87 does not fix this issue, it was spawned from that PR, but a new PR is needed. https://github.com/react-hook-form/error-message/pull/87/files/f0d5c51b3d04006eaa6bf19ed7224a312cbdb0f6#r762061758

I think this should be re-opened.
