### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by baldash** [react-hook-form/error-message#9]
Hi all,

First of all, thanks a lot for providing us with a tool like this, it's a really good idea.

However, I can't seem to make it work, for some reason it keeps saying Object(...) is not a function.

I followed the basic example in the doc, here is my code:

https://jsfiddle.net/qa846skp/

(used fiddle just for the colors)

And the error:
![error](https://user-images.githubusercontent.com/20284898/84761859-586cc780-afca-11ea-8f5d-56f7634105c1.png)

**Comment by bluebill1049** [comment]
hey @baldash which version are you using? can you share the version that you are using?

both react hook form and error message version. it would be great if you can supply a codesandbox as well, easier for us to reproduce issue.

**Comment by baldash** [comment]
Error messages: 0.0.2
React hook forms: 5.7.2

I'm not able to provide a code sand box for now but will do !

**Comment by bluebill1049** [comment]
hey @baldash ErrorMessage is part of V5, you don't need to use this lib. This is made for V6.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#ErrorMessage

**Comment by baldash** [comment]
oh, my bad, I need to read the doc better...

Thanks a lot for the help!
